name: "JOSE Actions"
description: "Javascript Object Signing and Encryption (JOSE) with GitHub Actions."
inputs:
  resource:
    description: "The resource to perform an action on"
    required: true
  action:
    description: "The action to perform"
    required: true

  header:
    description: "A JWS header as JSON"
    required: false
  payload:
    description: "A JWS payload as JSON"
    required: false
  jwk:
    description: "A JWK as JSON"
    required: false
  jws:
    description: "A Compact JWS"
    required: false


outputs:
  jws:
    description: "A Compact JWS"
    
runs:
  using: "node16"
  main: "dist/index.js"