name: CI

on: [push]

jobs:

  sign:
    concurrency: sign
    name: Sign a JWS
    runs-on: ubuntu-latest
    steps:
      - name: checking out repo
        uses: actions/checkout@v2

      - name: Sign
        id: sign_jws
        uses: or13/jose-actions@v0.0.5
        with:
          resource: "jws"
          action: "sign"
          
          header: '{"kid":"did:example123#0","alg":"ES256"}'
          payload: 'sha512-sFcuivsDZ99fY0TbvuRC6CDXB8r/ylafjJAMnbSF0y4EMM1/1DtQo40G2WKz1rBbyiz4SLAc3Wa6yZyC4XSGOQ=='
          jwk: '{"kty":"EC","crv":"P-256","alg":"ES256","d":"SoJ4K2QzbSkJkSWEW-e7I11kn4mT5xUVvIq5rDqqUWU","x":"SaGJIWK7l4PE9z97fY0_J5fX8Y971xtfrQDhnkAYERQ","y":"HkEanI5mtHyEYLkEiYXwcRuxviTS5e3rgi0kAzJZWkU"}'

      - name: View JWS
        run: echo "${{ steps.sign_jws.outputs.jws }}"
          
